### ISSUE TITLE
Missing build-dependency

### ISSUE THREAD

**Issue by ghost** [Linaro/pkg-django-compat#2]
Looks like django-compat wasn't checked in a pbuilder/schroot build.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797231

https://paste.debian.net/309553/ 

(This adds me as an uploader as well - using the list as the maintainer 
just ensures that everyone gets email, uploaders using the list still need to be listed to do a normal upload.)

**Comment by stylesen** [comment]
The patch https://paste.debian.net/309553/ expired. Hence will fix it as per requirement and upload the new debian package.

**Comment by stylesen** [comment]
Uploaded the package after making necessary fixes - http://lists.alioth.debian.org/pipermail/pkg-linaro-lava-devel/Week-of-Mon-20150824/000440.html
